// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAYX8cDAfBf3fjOBkY_qpQ0mAIU7t13nU',
    appId: '1:925296867254:web:5ee718fabc041ca7257317',
    messagingSenderId: '925296867254',
    projectId: 'device-streaming-c0540223',
    authDomain: 'device-streaming-c0540223.firebaseapp.com',
    storageBucket: 'device-streaming-c0540223.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsjbvCmrSV6Ge2pE6xSfL3wQoIbjsVHqI',
    appId: '1:925296867254:android:06c8ca6b05755264257317',
    messagingSenderId: '925296867254',
    projectId: 'device-streaming-c0540223',
    storageBucket: 'device-streaming-c0540223.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUtqLojKk4d3ReRpqwzTl7GGbAoTYDMW4',
    appId: '1:925296867254:ios:601a7947f6f248ea257317',
    messagingSenderId: '925296867254',
    projectId: 'device-streaming-c0540223',
    storageBucket: 'device-streaming-c0540223.firebasestorage.app',
    iosBundleId: 'com.example.integrationBd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUtqLojKk4d3ReRpqwzTl7GGbAoTYDMW4',
    appId: '1:925296867254:ios:601a7947f6f248ea257317',
    messagingSenderId: '925296867254',
    projectId: 'device-streaming-c0540223',
    storageBucket: 'device-streaming-c0540223.firebasestorage.app',
    iosBundleId: 'com.example.integrationBd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAYX8cDAfBf3fjOBkY_qpQ0mAIU7t13nU',
    appId: '1:925296867254:web:68bf60056bd09984257317',
    messagingSenderId: '925296867254',
    projectId: 'device-streaming-c0540223',
    authDomain: 'device-streaming-c0540223.firebaseapp.com',
    storageBucket: 'device-streaming-c0540223.firebasestorage.app',
  );
}
